### PR TITLE
Typings - fixes for typescript@2.7.1

### PR DESCRIPTION
**Pull request by iyegoroff**
Previous approach was based on erroneous compiler behavior, when defaults were treated as constraints - Microsoft/TypeScript#21632

### CODE REVIEW

**Comment by iyegoroff** [comment]
Done

**Comment by nkbt** [comment]
If you do rebase and `push --force` (force important), you will not have those `Merge branch 'master' into typings` things in history. It will cleanup all these extra empty commits.

**Comment by iyegoroff** [comment]
I switched to master before `push --force` and then merged it with typings branch.

**Comment by nkbt** [comment]
This is not `rebase` =)

here is your full workflow with rebase:
```sh
git checkout mybranch
git fetch upstream
git rebase upstream/master
git push --force origin mybranch
```
In this case you will have clean history in your branch without any cross-links (merges). So `git merge` is actually never needed.

**Pull request closed without merging**
