### PR TITLE
Fix #86 and #62: handle 0 as default value

### LINKED ISSUE #86: Doesn't accept 0 as 'value'
```javascript 
<DebounceInput value={0} />
```

renders empty input

### PR DESCRIPTION
**Pull request by Thiht**
Fix #86 and #62 

Before fix:

Capture d’écran 2020-10-26 à 23 50 53

After fix:

Capture d’écran 2020-10-26 à 23 51 07

Note: I also gave it a try with the `??` operator but got the following error:

> SyntaxError: /Users/thiht/workspace/react-debounce-input/src/Component.js: Support for the experimental syntax 'nullishCoalescingOperator' isn't currently enabled

so I just went with the less fancy solution instead

### CODE REVIEW

**Review by nkbt — APPROVED** [review]

**Comment by nkbt** [comment]
Well, good news CI still works ¯\_(ツ)_/¯

image

**Comment by Thiht** [comment]
Can you merge or is there any remaining blocking point ? :)

**Comment by nkbt** [comment]
CI check fails because of lint errors in this change, so I was waiting for that fix.

**Comment by Thiht** [comment]
oh sorry I didn't see it was from the component I added, I thought it was already red before! Will fix this evening.

**Comment by Thiht** [comment]
fixed

**Comment by nkbt** [comment]
image

**Comment by Thiht** [comment]
Thanks :+1:

**Comment by nkbt** [comment]
Thank you 🙏

**Pull request merged**
