### PR TITLE
allow adding onBlur and onKeyPress to element without force notify

### PR DESCRIPTION
**Pull request by Data-Meister**
Currently it is ignoring onBlur and onKeyPress handlers unless you have forceNotifyOnBlur or forceNotifyByEnter set, respectively

### CODE REVIEW

**Comment by nkbt** [comment]
I think my ci config is broken so it does not fail. Please run linter manually if you eish to see errors...

**Comment by Data-Meister** [comment]
OK, have updated the code.

**Comment by nkbt** [comment]
Still heaps :(

Might not be yours tho. I'll check when I'm on my laptop...

> react-debounce-input@3.0.0 start /home/ubuntu/react-debounce-input
> react-component-template "ci.lint"

nps executing: eslint /home/ubuntu/react-debounce-input

/home/ubuntu/react-debounce-input/src/Component.js
  153:1   error  Trailing spaces not allowed                                                   no-trailing-spaces
  154:28  error  Missing space before opening brace                                            space-before-blocks
  165:8   error  Missing semicolon                                                             semi
  166:5   error  Closing curly brace does not appear on the same line as the subsequent block  brace-style
  167:24  error  Missing space before opening brace                                            space-before-blocks
  168:35  error  Missing semicolon                                                             semi
  169:5   error  Closing curly brace does not appear on the same line as the subsequent block  brace-style
  171:26  error  Missing semicolon                                                             semi
  174:1   error  Trailing spaces not allowed                                                   no-trailing-spaces
  176:1   error  Trailing spaces not allowed                                                   no-trailing-spaces
  177:27  error  Missing space before opening brace                                            space-before-blocks
  186:8   error  Missing semicolon                                                             semi
  187:5   error  Closing curly brace does not appear on the same line as the subsequent block  brace-style
  188:21  error  Missing space before opening brace                                            space-before-blocks
  189:29  error  Missing semicolon                                                             semi
  190:5   error  Closing curly brace does not appear on the same line as the subsequent block  brace-style
  192:23  error  Missing semicolon                                                             semi

/home/ubuntu/react-debounce-input/src/example/App/UndoRedo.js
  31:25  error  Unexpected parentheses around single function argument  arrow-parens

✖ 18 problems (18 errors, 0 warnings)

**Comment by Data-Meister** [comment]
Have submitted another commit. It was Previously calling `.cancel()` and `.flush()` on `this.notify`. Now it's calling those methods on `debouncedChangeFunc` - so it should fix issue #64

**Comment by Data-Meister** [comment]
Hi there, I notice you've approved this PR, but I don't think it's been merged yet. Are you happy to merge it?

**Comment by nkbt** [comment]
Yeah, as soon as lint errors are fixed =)

```
/home/ubuntu/react-debounce-input/src/Component.js
   86:21  error  Missing space before =>                                                       arrow-spacing
   90:22  error  Missing space before =>                                                       arrow-spacing
  162:28  error  Missing space before opening brace                                            space-before-blocks
  173:8   error  Missing semicolon                                                             semi
  174:5   error  Closing curly brace does not appear on the same line as the subsequent block  brace-style
  175:24  error  Missing space before opening brace                                            space-before-blocks
  176:35  error  Missing semicolon                                                             semi
  177:5   error  Closing curly brace does not appear on the same line as the subsequent block  brace-style
  179:26  error  Missing semicolon                                                             semi
  185:27  error  Missing space before opening brace                                            space-before-blocks
  194:8   error  Missing semicolon                                                             semi
  195:5   error  Closing curly brace does not appear on the same line as the subsequent block  brace-style
  196:21  error  Missing space before opening brace                                            space-before-blocks
  197:29  error  Missing semicolon                                                             semi
  198:5   error  Closing curly brace does not appear on the same line as the subsequent block  brace-style
  200:23  error  Missing semicolon                                                             semi

/home/ubuntu/react-debounce-input/src/example/App/UndoRedo.js
  31:25  error  Unexpected parentheses around single function argument  arrow-parens

✖ 17 problems (17 errors, 0 warnings)
```

The problem is that `p-s` ignores errors and exits with code 0, this is why CI is always happy =(

I need to update the build here to get rid of this annoying issue

**Comment by Data-Meister** [comment]
Have done :)

**Comment by nkbt** [comment]
Published + react-debounce-input@3.0.1

**Pull request merged**
